name: "Family Household Manager"
version: "1.0.0"
slug: family-chores
description: "Self-hosted household management for families"
arch:
  - amd64
  - armhf
  - armv7
  - aarch64
ingress: true
ingress_port: 3000
ingress_stream: true
panel_icon: "mdi:clipboard-check-multiple"
panel_title: "Family Manager"
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: "Web interface (direct access)"
webui: "http://[HOST]:[PORT:3000]"
startup: application
boot: auto
init: false
map:
  - data:rw
